services:
  datadog-agent:
    image: "gcr.io/datadoghq/agent:7"
    container_name: datadog-agent
    environment:
      - DD_ENV=otel
      - DD_API_KEY
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_LOG_LEVEL=WARN
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_DOGSTATSD_SOCKET=/var/run/datadog/dsd.socket
      - DD_APM_RECEIVER_SOCKET=/var/run/datadog/apm.socket
      - DD_APM_COMPUTE_STATS_BY_SPAN_KIND=true 
      - DD_APM_PEER_TAGS_AGGREGATION=true
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT=0.0.0.0:4317
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT=0.0.0.0:4318
    ports:
      - "8126:8126"
      - "8125:8125"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/run/datadog:/var/run/datadog

  node-api:
    build: node-api/
    depends_on:
      - datadog-agent
    container_name: node-api
    ports:
      - 3000:3000
    labels:
      com.datadoghq.ad.logs: '[{ "source": "javascript", "service": "node-api"}]'
      com.datadoghq.tags.service: 'node-api'
      com.datadoghq.tags.env: 'otel'
      com.datadoghq.tags.version: '2.0'  
    environment:
      - DD_LOGS_INJECTION=true
      - DD_AGENT_HOST=datadog-agent
      - DD_RUNTIME_METRICS_ENABLED=true
      - DD_SERVICE=node-api
      - DD_VERSION=2.0
      - DD_TRACE_REMOVE_INTEGRATION_SERVICE_NAMES_ENABLED=true
      - DD_TRACE_OTEL_ENABLED=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://datadog-agent:4318
      - NODE_OPTIONS=--require dd-trace/init
      #- OTEL_LOG_LEVEL=debug
    volumes:
      - /var/run/datadog:/var/run/datadog:ro